# Generated by Django 2.2.27 on 2022-02-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuboidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_a', models.FloatField()),
                ('edge_b', models.FloatField()),
                ('edge_c', models.FloatField()),
                ('surface_area', models.FloatField()),
                ('volume', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('addedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': "Calculation's ",
                'ordering': ('addedDate',),
                'verbose_name_plural': "Calculation's",
            },
        ),
    ]
